# The URL the site will be built for
base_url = "https://youthful-bhaskara-d642d0.netlify.com"
generate_rss = true
compile_sass = true
theme = "zola-clean-blog"
title = "Basetta.bz"
description = "Personal and technical musings"
highlight_code = true

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Basetta"
keywords = "web, android, technology, docker, javascript, java, python, blog, computer engineering, shaleen jain, shalzz, shaleen, jain, C/C++, rust, C, C++, GO-lang"

clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"}
]
clean_blog_social = [
    {url = "https://twitter.com", icon="fab fa-twitter"},
    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
]

